name: CPU

on:
  pull_request_target:
    # triggered on pull requests to main or develop
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
    tags:
      - v*

env:
  IMAGE_NAME: mala_conda_cpu

jobs:
  # Build and push Docker temporary image to GitHub Packages.
  build-docker-temp-image-cpu:
    runs-on: ubuntu-18.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set environment variables
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          echo github.repository_owner = "${{ github.repository_owner }}"
          echo GITHUB_RUN_ID = "${GITHUB_RUN_ID}"

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Create environment variable to which all subsequent actions in this job have access
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Pull latest image from registry
        run: docker pull $IMAGE_ID || true

      - name: Build temporary image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --cache-from=$IMAGE_ID --build-arg DEVICE=cpu --label "runnumber=${GITHUB_RUN_ID}"

      - name: Tag and push temporary image
        run: |
          # print github.ref contexts (for debugging)
          echo github.head_ref = "${{ github.head_ref }}"
          echo github.ref = "${{ github.ref }}"
          echo github.ref_name = "${{ github.ref_name }}"

          # use Docker ... tag
          TAG=temp

          echo IMAGE_ID=$IMAGE_ID
          echo TAG=$TAG

          docker tag $IMAGE_NAME $IMAGE_ID:$TAG
          docker push $IMAGE_ID:$TAG

  cpu-tests:
    needs: build-docker-temp-image-cpu
    runs-on: ubuntu-18.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/mala_conda_cpu:temp
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository (mala)
        uses: actions/checkout@v2

      - name: Show os-release
        run: cat /etc/os-release

      - name: Tag and push Docker image
        run: echo "DOCKER_TAG=$(echo ${{ github.ref }} | cut -d'/' -f3- | sed 's/[^a-z0-9_-]/__/gi')"

