name: CPU tests new

on:
  pull_request:
    # Trigger on pull requests to main or develop
    branches:
      - main
      - develop
  push:
    # Trigger on pushes to main or develop and for git tag pushes
    branches:
      - main
      - develop
    tags:
      - v*

env:
  IMAGE_NAME: mala_conda_cpu_new
  IMAGE_REPO: ghcr.io/${{ github.repository_owner }}

jobs:
  build-temp-docker-image-cpu:
    # Build and push temporary Docker image to GitHub's container registry
    runs-on: ubuntu-18.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set environment variables
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=$IMAGE_ID"

          # Create environment variable to which any subsequent steps in a workflow job have access
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Pull latest image from registry
        run: docker pull $IMAGE_ID || true

      - name: Build temporary image
        id: build-temp
        run: |
          docker build . --file Dockerfile --tag $IMAGE_NAME --cache-from=$IMAGE_ID --build-arg DEVICE=cpu

          # Get image IDs (hash of the local image JSON configuration) and check if images are equal
          IMAGE_ID_OLD=$(docker images --format "{{.ID}}" --no-trunc --filter=reference=$IMAGE_ID)
          IMAGE_ID_NEW=$(docker images --format "{{.ID}}" --no-trunc --filter=reference=$IMAGE_NAME)

          echo "IMAGE_ID_OLD=$IMAGE_ID_OLD" >> $GITHUB_ENV
          echo "IMAGE_ID_NEW=$IMAGE_ID_NEW" >> $GITHUB_ENV

          if [[ "$IMAGE_ID_OLD" == "$IMAGE_ID_NEW" ]]
          then
            echo "Image IDs are equal"
            echo "::set-output name=IMAGE_IDS_EQUAL::true" # TODO: line possibly obsolete
          else
            echo "Image IDs differ"
            echo "::set-output name=IMAGE_IDS_EQUAL::false" # TODO: line possibly obsolete
          fi

          docker images # TODO: remove line

      - name: Tag temporary Docker image
        if: env.IMAGE_ID_OLD != env.IMAGE_ID_NEW
        run: |
          # Print some environment variables from the github context (for debugging)
          echo "github.head_ref=${{ github.head_ref }}"
          echo "github.ref=${{ github.ref }}"
          echo "github.ref_name=${{ github.ref_name }}"
          echo "github.repository_owner=${{ github.repository_owner }}"
          echo "github.run_id=${{ github.run_id }}"

          mkdir -p artifacts/docker # TODO: make this path available among jobs

          # if temporary image is different from latest
          if [[ "$IMAGE_ID_OLD" != "$IMAGE_ID_NEW" ]]
          then
            # Use GITHUB_RUN_ID, a unique number for each workflow run within a repository as a temporary Docker tag
            #docker tag $IMAGE_NAME $IMAGE_ID:$GITHUB_RUN_ID
            docker tag $IMAGE_NAME $IMAGE_NAME:$GITHUB_RUN_ID

            #docker push $IMAGE_ID:$GITHUB_RUN_ID
            docker save $IMAGE_NAME:$GITHUB_RUN_ID | gzip > artifacts/docker/docker-image.tar.gz
          else
            docker save $IMAGE_NAME:latest | gzip > artifacts/docker/docker-image.tar.gz # TODO: obsolete
          fi

      - name: Temporarily save Docker image
        if: env.IMAGE_ID_OLD != env.IMAGE_ID_NEW
        uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: artifacts/docker
          retention-days: 1

      - name: Set matrix
        id: set-matrix
        run: |
          if [[ "$IMAGE_ID_OLD" == "$IMAGE_ID_NEW" ]]
          then
            echo "::set-output name=matrix::[\"latest\"]"
          else
            echo "::set-output name=matrix::[\"${{ github.run_id }}\"]"
          fi

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      equal: ${{ steps.build-temp.outputs.IMAGE_IDS_EQUAL }} # TODO: remove this line

  check-output:
    needs: build-temp-docker-image-cpu
    runs-on: ubuntu-18.04
    steps:
      - run: |
          echo "matrix=${{needs.build-temp-docker-image-cpu.outputs.matrix}}"
          echo "equal=${{needs.build-temp-docker-image-cpu.outputs.equal}}"
          [[ ${{ (github.event_name == 'push') }} ]] && echo "TRUE"  || true
          [[ ${{ (needs.build-temp-docker-image-cpu.outputs.equal == 'false') }} ]] && echo "TRUE" || true
          [[ ${{ (github.event_name == 'push') && (needs.build-temp-docker-image-cpu.outputs.equal == 'false') }} ]] && echo "TRUE" || true
          [[ ${{ (contains(github.ref_name, 'develop') || contains(github.ref_name, 'main')) }} ]] && echo "contain TRUE" || true

  cpu-tests:
    needs: build-temp-docker-image-cpu
    runs-on: ubuntu-18.04
    strategy:
      matrix:
       version: ${{ fromJSON(needs.build-temp-docker-image-cpu.outputs.matrix) }}
    #container:
    #  image: ghcr.io/${{ github.repository_owner }}/mala_conda_cpu_new:${{ matrix.version }}
    #  credentials:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository (mala)
        uses: actions/checkout@v2

      - name: Retrieve saved artifactes
        if: matrix.version != 'latest'
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: artifacts/docker

      - name: Load Docker image from artifacts
        if: matrix.version != 'latest'
        run: |
          cd artifacts/docker
          docker load < docker-image.tar.gz
          docker images # TODO: remove line

      - name: Pull latest image from registry
        if: matrix.version == 'latest'
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          docker images
          docker image tag ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME $IMAGE_NAME:latest
          docker images
          docker ps

      - name: Run Docker image
        run: |
          # make the github workspace (i.e. checked out mala repository) available inside Docker container
          docker run -i -d --name mala -v /github/workspace/:/home -w /home mala_conda_cpu_new:${{ matrix.version }}
#          docker run -i -d --name mala -w /home mala_conda_cpu_new

      - name: Show some Docker container specifics
        run: |
          docker exec -i mala bash
          ls -lah
          tree
          cat /etc/os-release

  retag-temp-docker-image-cpu:
    needs: [cpu-tests, build-temp-docker-image-cpu]
    runs-on: ubuntu-18.04
    # Trigger on pushes to main or develop (this includes _merged_ PRs) only if Docker image has changed and on git tag pushes
    if:  ((contains(github.ref_name, 'develop') || contains(github.ref_name, 'main')) && needs.build-temp-docker-image-cpu.outputs.equal == 'false') || startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
       version: ${{ fromJSON(needs.build-temp-docker-image-cpu.outputs.matrix) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull temp image from registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          docker pull $IMAGE_ID:${{ matrix.version }}

      - name: Tag Docker image
        run: |
          # on change of Docker image
          if ${{ needs.build-temp-docker-image-cpu.outputs.equal == 'false' }}; then
            GIT_SHA=${GITHUB_REF_NAME}-$(git rev-parse --short "$GITHUB_SHA")
            echo "GIT_SHA=$GIT_SHA"

            docker tag $IMAGE_ID:$GITHUB_RUN_ID $IMAGE_ID:$GIT_SHA
            docker tag $IMAGE_ID:$GITHUB_RUN_ID $IMAGE_ID:latest
          fi

          # on push of git tag
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            GIT_TAG=$(echo "${{ github.ref_name }}" | sed -e 's/^v//')
            echo "GIT_TAG=$GIT_TAG"

            docker tag $IMAGE_ID:latest $IMAGE_ID:$GIT_TAG
          fi

      - name: Push Docker image
        run: docker push $IMAGE_ID --all-tags

  cleanup:
    # Remove intermediate Docker image from ghcr.io
    runs-on: ubuntu-18.04
    #needs: cpu-tests
    # FIXME: In the future, this workflow should _always_ be triggered ('always()') rather than skipped ('false').
    #        We currently skip it as the 'ghcr-delet-image-action' does not support GITHUB_TOKEN. It actually
    #        finds the image in the registry, but can't delete it and fails with cryptic 'Error: Package not found.'
    #        This is expected to change at some point.
    if: false #always()
    steps:
      - name: Delete temporary image
        uses: bots-house/ghcr-delete-image-action@v1.0.1
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ env.IMAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}  # <-- GITHUB_TOKEN is currently not supported (only PATs)
          tag: ${{ github.run_id }}
