name: Docker test

on:
  pull_request:
    # Trigger on pull requests to master or develop
    branches:
      - main
      - develop
  push:
    # Trigger on pushes to master or develop and for git tag pushes
    branches:
      - main
      - develop


jobs:
  docker-example:
    runs-on: ubuntu-18.04
    steps:
      - name: foo
        run: |
            docker images
            docker pull ghcr.io/testdockerorga/mala_conda_cpu:main-00732c9
            docker images
            docker run -i -d --rm --name mala-cpu -v ${{ github.workspace }}:/home -w /home ghcr.io/testdockerorga/mala_conda_cpu
            echo "Exit code: $?"
            docker ps --all
