name: Docker test

on:
  pull_request:
    # Trigger on pull requests to master or develop
    branches:
      - main
      - develop
  push:
    # Trigger on pushes to master or develop and for git tag pushes
    branches:
      - main
      - develop


jobs:
  docker-example:
    runs-on: ubuntu-18.04
    steps:
      - name: foo
        run: docker images
